# Generated by Django 3.0.5 on 2020-04-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=32)),
                ('userName', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=128)),
                ('duty', models.CharField(choices=[('BAK', 'Backend Engineer'), ('FRO', 'Frontend Engineer'), ('DEV', 'DevOps Engineer'), ('DES', 'Designer'), ('CSX', 'Customer Support / Customer Experience'), ('PM', 'Project Manager')], max_length=3)),
            ],
        ),
    ]
